import { TimelineMilestone, EventDetail, GalleryItem } from '../types';


export const weddingContent = {
  couple: {
    groom: 'Sir Edwin',
    bride: 'Lady Ilétou',
    monogram: 'E & I',
    subheading: 'Célèbrent leur union',
  },
  date: {
    formatted: 'Septembre 2026',
    time: '10h00',
    isoDate: '2026-09-12T10:00:00',
    year: '2026',
    locationShort: 'Lomé, Togo',
    religieux: {
      label: 'Mariage',
      formatted: 'Samedi 12 Septembre 2026',
      shortDate: '12 SEPT. 2026',
      isoDate: '2026-09-12T10:00:00',
    },
  },
  venue: {
    name: 'Lieu du rafraîchissement',
    address: 'Lomé, Togo',
    city: 'Lomé, Togo',
    googleMapsUrl: 'https://maps.app.goo.gl/mM4XaDG3Au15DqHUA',
    imageUrl: '/photos/lieu.jpg',
    coordinates: { lat: 6.3344, lng: 1.2178 },
  },
  preloader: {
    welcomeText: 'Bienvenue au mariage de',
    monogram: 'E & I',
    subtitle: 'Veuillez patienter pendant le chargement de notre univers...',
  },
  hero: {
    eyebrow: 'Nous avons la joie de vous inviter à notre mariage',
    title: 'Sir Edwin & Lady Ilétou',
    dateBadge: '12 SEPTEMBRE 2026',
    venueBadge: 'LOMÉ, TOGO',
    ctaRsvp: 'Confirmer votre présence',
    ctaStory: 'Découvrir notre histoire',
    scrollNotice: 'Faites défiler pour découvrir notre histoire',
  },
  timeline: {
    eyebrow: 'Notre Roman',
    title: 'Notre Histoire',
    subtitle: 'Chaque grand amour commence par une étincelle et s’épanouit au fil du temps.',
    milestones: [
      {
        id: 'meeting',
        year: '2019',
        date: '14 Octobre 2019',
        title: 'La Première Rencontre',
        location: 'Lomé, Togo',
        description: 'Un moment simple qui a marqué le début d’une belle histoire. Depuis, notre complicité n’a cessé de grandir.',
        imageUrl: '/photos/histoire.jpeg',
      },
      {
        id: 'proposal',
        year: '2026',
        date: '2026',
        title: 'Une nouvelle étape',
        location: 'Lomé, Togo',
        description: 'Notre histoire continue de s’écrire avec amour, confiance et la joie de construire notre avenir ensemble.',
        imageUrl: '/photos/dot.jpeg',
      },
      {
        id: 'wedding',
        year: '2026',
        date: '12 Septembre 2026',
        title: 'Le Grand Jour',
        location: 'Lomé, Togo',
        description: 'Nous sommes impatients de sceller notre amour entourés de nos familles et amis les plus chers.',
        imageUrl: '/photos/tgt.jpeg',
      },
    ] as TimelineMilestone[],
  },
  events: {
    eyebrow: 'Déroulement de la Journée',
    title: 'Programme & Informations',
    subtitle: 'Tous les détails essentiels pour vivre ce moment à nos côtés.',
    colorTheme: {
      title: 'Thème de couleurs',
      description: 'Nous vous invitons simplement à porter une touche de vert sauge, de rouge intense ou de blanc ivoire dans votre tenue.',
    },
    items: [
      {
        id: 'ceremony',
        time: '10h00',
        title: 'Cérémonie nuptiale',
        locationName: 'Lomé, Togo',
        address: 'Les informations pratiques seront communiquées aux invités.',
        description: 'Un moment de bénédiction et de célébration de notre union avec nos familles et nos proches.',
        iconName: 'church',
      },
      {
        id: 'refreshments',
        time: 'Après la cérémonie',
        title: 'Rafraîchissement',
        locationName: 'Lomé, Togo',
        address: 'Lieu du rassemblement',
        description: 'Un temps convivial autour de rafraîchissements juste après la cérémonie.',
        iconName: 'cheers',
      },
    ] as EventDetail[],
  },
  gallery: {
    eyebrow: 'Moments Précieux',
    title: 'Galerie Souvenirs',
    subtitle: 'Quelques clichés de notre histoire. Les photos définitives peuvent être ajoutées dans le dossier public/photos.',
    categories: [
      { id: 'all', label: 'Tous les clichés' },
      { id: 'histoire', label: 'Notre Histoire' },
      { id: 'fiancailles', label: 'Fiançailles' },
      { id: 'lieu', label: 'Le Lieu' },
    ],
    items: [
      {
        id: '1',
        title: 'Notre histoire',
        category: 'histoire',
        imageUrl: '/photos/sir.jpeg',
        caption: 'Ajoutez ici la première photo dans public/photos/.',
      },
      {
        id: '2',
        title: 'Un moment précieux',
        category: 'histoire',
        imageUrl: '/photos/iletou.jpeg',
        caption: 'Ajoutez ici la deuxième photo dans public/photos/.',
      },
      {
        id: '3',
        title: 'Fiançailles',
        category: 'fiancailles',
        imageUrl: '/photos/tgt.jpeg',
        caption: 'Ajoutez ici une photo de vos fiançailles.',
      },
      {
        id: '4',
        title: 'À deux',
        category: 'histoire',
        imageUrl: '/photos/couple.jpeg',
        caption: 'Ajoutez ici une photo de votre choix.',
      },
      {
        id: '5',
        title: 'Souvenir',
        category: 'fiancailles',
        imageUrl: '/photos/rouge.jpeg',
        caption: 'Ajoutez ici une dernière photo souvenir.',
      },
    ] as GalleryItem[],
  },
  gifts: {
    title: 'Cadeaux & Cagnotte',
    description: 'Vous êtes nombreux à faire le déplacement, parfois de très loin, pour partager avec nous ce moment si précieux et célébrer notre union. Votre présence à nos côtés constitue à elle seule le plus beau des cadeaux et nous comble de bonheur. Toutefois, si vous souhaitez également nous témoigner votre affection à travers une attention particulière, vous pourrez, selon votre convenance, participer à notre cagnotte de la manière qui vous sera la plus simple, par virement bancaire, transfert d\'argent via Mix, Payas ou Mov Money, ou encore par un cadeau physique. Quelle que soit la forme choisie, votre geste nous touchera profondément et restera précieux à nos yeux. Avec toute notre gratitude et notre affection, merci de célébrer cet amour avec nous.',
    onlineFundUrl: '',
    onlineFundLabel: 'Participer à la cagnotte en ligne',
  },
  rsvp: {
    eyebrow: 'Votre Réponse',
    title: 'Confirmer Votre Présence',
    subtitle: 'Merci de nous indiquer votre réponse avant le 5 Septembre 2026 afin de nous aider à tout orchestrer.',
    deadline: 'Réponse souhaitée avant le 5 Septembre 2026',
    fields: {
      lastName: 'Nom de famille',
      firstName: 'Prénom',
      email: 'Adresse E-mail',
      attending: 'Serez-vous parmi nous ?',
      yesOption: 'Oui, avec grand plaisir !',
      noOption: 'Non, c’est avec regret que je ne pourrai venir',
      guestCount: 'Nombre de personnes (vous inclus)',
      guestNames: 'Noms et prénoms des accompagnants',
      message: 'Un petit mot pour les mariés',
      submitBtn: 'Envoyer ma réponse',
      sendingBtn: 'Enregistrement en cours...',
    },
    successMessage: {
      title: 'Merci infiniment !',
      description: 'Votre réponse a bien été enregistrée. Nous avons tellement hâte de célébrer ce moment inoubliable avec vous !',
      modifyBtn: 'Modifier mes informations',
    },
  },
  footer: {
    thankYou: 'Merci du fond du cœur',
    quote: '« Aimer, ce n’est pas se regarder l’un l’autre, c’est regarder ensemble dans la même direction. »',
    author: 'Antoine de Saint-Exupéry',
    contactTitle: 'Une question ? Besoin d’aide ?',
    contactDetails: 'Écrivez-nous à iletouakpo@gmail.com ou contactez nos témoins.',
    copyright: '© 2026 Edwin & Julie — Avec tout notre amour',
  },
};
