import { TimelineMilestone, EventDetail, GalleryItem } from '../types';

import couplePortrait from '../assets/images/couple_portrait_1786119743503.jpg';
import chateauVenue from '../assets/images/chateau_venue_1786119755416.jpg';
import weddingRings from '../assets/images/wedding_rings_1786119768056.jpg';

export const weddingContent = {
  couple: {
    groom: 'Edwin',
    bride: 'Julie',
    monogram: 'E & J',
    subheading: 'Célèbrent leur union',
  },
  date: {
    formatted: 'Septembre 2026',
    time: '10h00',
    isoDate: '2026-09-12T10:00:00',
    year: '2026',
    locationShort: 'Provence, France',
    civil: {
      label: 'Mariage Civil',
      formatted: 'Jeudi 10 Septembre 2026',
      shortDate: '10 SEPT. 2026',
      isoDate: '2026-09-10T10:00:00',
    },
    religieux: {
      label: 'Mariage Religieux',
      formatted: 'Samedi 12 Septembre 2026',
      shortDate: '12 SEPT. 2026',
      isoDate: '2026-09-12T10:00:00',
    },
  },
  venue: {
    name: 'Winners Chapel International Lome',
    address: 'Avenue de la paix, Lome Aeroport, Togo',
    city: 'Lome, Togo',
    googleMapsUrl: 'https://maps.google.com/?q=Winners+Chapel+International+Lome',
    coordinates: { lat: 6.3344, lng: 1.2178 },
  },
  preloader: {
    welcomeText: 'Bienvenue au mariage de',
    monogram: 'E & J',
    subtitle: 'Veuillez patienter pendant le chargement de notre univers...',
  },
  hero: {
    eyebrow: 'Nous avons la joie de vous inviter à notre mariage',
    title: 'Edwin & Julie',
    dateBadge: '10 & 12 SEPTEMBRE 2026',
    venueBadge: 'WINNERS CHAPEL INT\'L LOME',
    ctaRsvp: 'Confirmer votre présence',
    ctaStory: 'Découvrir notre histoire',
    scrollNotice: 'Faites défiler pour suivre notre voyage',
  },
  timeline: {
    eyebrow: 'Notre Roman',
    title: 'Notre Histoire',
    subtitle: 'Chaque grand amour commence par une étincelle et s’épanouit au fil du temps.',
    milestones: [
      {
        id: 'meeting',
        year: '2019',
        date: '14 Octobre 2019',
        title: 'La Première Rencontre',
        location: 'Lome, Togo',
        description: 'Un café improvisé sur les quais de Seine un après-midi d’automne. Ce qui devait être une simple pause café s’est transformé en une conversation captivante jusqu’au coucher du soleil.',
        imageUrl: couplePortrait,
      },
      {
        id: 'travel',
        year: '2023',
        date: '18 Juin 2023',
        title: 'Le Premier Grand Voyage',
        location: 'Lome, Togo',
        description: 'Une escapade enchanteresse le long de la côte amalfitaine. Entre routes serpentées, citrons frais et soirées bercées par les vagues, nous avons su que nous étions faits l’un pour l’autre.',
        imageUrl: weddingRings,
      },
      {
        id: 'proposal',
        year: '2026',
        date: '24 Septembre 2026',
        title: 'La Dote memorable',
        location: 'Lome, Togo',
        description: 'Au sommet des collines du Luberon, au milieu des parfums de lavande au crépuscule. Edwin a posé un genou à terre avec une bague étincelante et Julie a dit OUI sans hésiter.',
        imageUrl: chateauVenue,
      },
      {
        id: 'wedding',
        year: '2026',
        date: '12 Septembre 2026',
        title: 'Le Grand Jour',
        location: 'Winners Chapel International Lome',
        description: 'Nous sommes impatients de sceller notre amour entourés de nos familles et amis les plus chers.',
        imageUrl: couplePortrait,
      },
    ] as TimelineMilestone[],
  },
  events: {
    eyebrow: 'Déroulement de la Journée',
    title: 'Programme & Informations',
    subtitle: 'Tous les détails essentiels pour vivre ce moment magique à nos côtés.',
    dressCode: {
      title: 'Code Vestimentaire',
      description: 'Tenue Chic & Élégante aux tons de couleur vert sauge, rouge intense et blanc ivoire.',
    },
    items: [
      {
        id: 'ceremony',
        time: '10h00',
        title: 'Cérémonie de benediction nuptiale',
        locationName: 'Winners Chapel International Lome',
        address: 'Avenue de la paix, Lome Aeroport, Togo',
        description: 'Échange de nos vœux dans l\'auditorium de la chapelle des vainqueurs de Lome aeroport.',
        iconName: 'church',
      },
      {
        id: 'cocktail',
        time: '12h00',
        title: 'Cocktail & Dégustations',
        locationName: '3e etage de la chapelle',
        address: 'Winners Chapel International Lome',
        description: 'Rafraîchissements, dégustations et musique.',
        iconName: 'cheers',
      },
    ] as EventDetail[],
  },
  gallery: {
    eyebrow: 'Moments Précieux',
    title: 'Galerie Souvenirs',
    subtitle: 'Quelques clichés immortalisant notre complicité à travers les années.',
    categories: [
      { id: 'all', label: 'Tous les clichés' },
      { id: 'histoire', label: 'Notre Histoire' },
      { id: 'fiancailles', label: 'Fiançailles' },
      { id: 'lieu', label: 'Le Lieu' },
    ],
    items: [
      {
        id: '1',
        title: 'Complices en Provence',
        category: 'fiancailles',
        imageUrl: couplePortrait,
        caption: 'Session engagement sous la lumière dorée du Luberon.',
      },
      {
        id: '2',
        title: 'Domaine de Saint-Germain',
        category: 'lieu',
        imageUrl: chateauVenue,
        caption: 'Le cadre d’exception où nous nous dirons Oui.',
      },
      {
        id: '3',
        title: 'Symbole d’Éternité',
        category: 'fiancailles',
        imageUrl: weddingRings,
        caption: 'Les alliances gravées de nos promesses.',
      },
      {
        id: '4',
        title: 'Regard vers l’Avenir',
        category: 'histoire',
        imageUrl: couplePortrait,
        caption: 'Deux cœurs unis dans la même direction.',
      },
      {
        id: '5',
        title: 'Champs de Lavande',
        category: 'lieu',
        imageUrl: chateauVenue,
        caption: 'Un parfum envoûtant qui bercera notre grande fête.',
      },
      {
        id: '6',
        title: 'Instants Précieux',
        category: 'fiancailles',
        imageUrl: weddingRings,
        caption: 'Savoir savourer chaque minute avant le grand jour.',
      },
    ] as GalleryItem[],
  },
  rsvp: {
    eyebrow: 'Votre Réponse',
    title: 'Confirmer Votre Présence',
    subtitle: 'Merci de nous indiquer votre réponse avant le 5 Septembre 2026 afin de nous aider à tout orchestrer.',
    deadline: 'Réponse souhaitée avant le 5 Septembre 2026',
    fields: {
      lastName: 'Nom de famille',
      firstName: 'Prénom',
      email: 'Adresse E-mail',
      attending: 'Serez-vous parmi nous ?',
      yesOption: 'Oui, avec grand plaisir !',
      noOption: 'Non, c’est avec regret que je ne pourrai venir',
      guestCount: 'Nombre de personnes (vous inclus)',
      guestNames: 'Noms et prénoms des accompagnants',
      message: 'Un petit mot pour les mariés',
      submitBtn: 'Envoyer ma réponse',
      sendingBtn: 'Enregistrement en cours...',
    },
    successMessage: {
      title: 'Merci infiniment !',
      description: 'Votre réponse a bien été enregistrée. Nous avons tellement hâte de célébrer ce moment inoubliable avec vous !',
      modifyBtn: 'Modifier mes informations',
    },
  },
  footer: {
    thankYou: 'Merci du fond du cœur',
    quote: '« Aimer, ce n’est pas se regarder l’un l’autre, c’est regarder ensemble dans la même direction. »',
    author: 'Antoine de Saint-Exupéry',
    contactTitle: 'Une question ? Besoin d’aide ?',
    contactDetails: 'Écrivez-nous à iletouakpo@gmail.com ou contactez nos témoins.',
    copyright: '© 2026 Edwin & Julie — Avec tout notre amour',
  },
};
