import { TimelineMilestone, EventDetail, GalleryItem } from '../types';


export const weddingContent = {
  couple: {
    groom: 'Sir Edwin',
    bride: 'Lady Ilétou',
    monogram: 'E & I',
    subheading: 'Célèbrent leur union',
  },
  date: {
    formatted: 'Septembre 2026',
    time: '10h00',
    isoDate: '2026-09-12T10:00:00',
    year: '2026',
    locationShort: 'Lomé, Togo',
    religieux: {
      label: 'Mariage',
      formatted: 'Samedi 12 Septembre 2026',
      shortDate: '12 SEPT. 2026',
      isoDate: '2026-09-12T10:00:00',
    },
  },
  venue: {
    name: 'Winner\'s Chapel International Lomé Aeroport',
    description: 'La cérémonie de bénédiction nuptiale se tiendra à Winner\'s Chapel International Lomé Aeroport.',
    address: 'Lomé, Togo',
    city: 'Lomé, Togo',
    googleMapsUrl: 'https://maps.app.goo.gl/mM4XaDG3Au15DqHUA',
    imageUrl: '/photos/wci.jpeg',
    coordinates: { lat: 6.3344, lng: 1.2178 },
  },
  preloader: {
    welcomeText: 'Bienvenue au mariage de',
    monogram: 'E & I',
    subtitle: 'Veuillez patienter pendant le chargement de notre univers...',
  },
  hero: {
    invitation: 'Ont le plaisir de vous inviter à leur cérémonie de bénédiction nuptiale',
    ceremonyDate: 'Le samedi 12 septembre 2026',
    coupleImageUrl: '/photos/hero-couple.jpg',
    venueBadge: 'LOMÉ, TOGO',
    ctaRsvp: 'Confirmer votre présence',
    ctaStory: 'Découvrir notre histoire',
    scrollNotice: 'Faites défiler pour découvrir notre histoire',
  },
  timeline: {
    eyebrow: 'Notre Roman',
    title: 'Notre Histoire',
    subtitle: 'Chaque grand amour commence par une étincelle et s’épanouit au fil du temps.',
    milestones: [
      {
        id: 'meeting',
        year: '2019',
        date: '14 Octobre 2019',
        title: 'La Première Rencontre',
        location: 'Lomé, Togo',
        description: 'Un moment simple qui a marqué le début d’une belle histoire. Depuis, notre complicité n’a cessé de grandir.',
        imageUrl: '/photos/histoire.jpeg',
      },
      {
        id: 'proposal',
        year: '2026',
        date: '2026',
        title: 'Une nouvelle étape',
        location: 'Lomé, Togo',
        description: 'Notre histoire continue de s’écrire avec amour, confiance et la joie de construire notre avenir ensemble.',
        imageUrl: '/photos/dot.jpeg',
      },
      {
        id: 'wedding',
        year: '2026',
        date: '12 Septembre 2026',
        title: 'Le Grand Jour',
        location: 'Lomé, Togo',
        description: 'Nous sommes impatients de sceller notre amour entourés de nos familles et amis les plus chers.',
        imageUrl: '/photos/tgt.jpeg',
      },
    ] as TimelineMilestone[],
  },
  events: {
    eyebrow: 'Déroulement de la Journée',
    title: 'Programme & Informations',
    subtitle: 'Tous les détails essentiels pour vivre ce moment à nos côtés.',
    items: [
      {
        id: 'ceremony',
        time: '10h00',
        title: 'Cérémonie de bénédiction nuptiale',
        locationName: 'Lomé, Togo',
        address: 'Les informations pratiques seront communiquées aux invités.',
        description: 'Un moment de bénédiction et de célébration de notre union avec nos familles et nos proches.',
        iconName: 'church',
      },
      {
        id: 'refreshments',
        time: 'Après la cérémonie',
        title: 'Rafraîchissement',
        locationName: 'Lomé, Togo',
        address: 'Lieu du rassemblement',
        description: 'Petit cocktail servi juste après la fin de la cérémonie.',
        iconName: 'cheers',
      },
    ] as EventDetail[],
  },
  gallery: {
    eyebrow: 'Moments Précieux',
    title: 'Galerie Souvenirs',
    subtitle: 'Quelques clichés de notre histoire. Les photos définitives peuvent être ajoutées dans le dossier public/photos.',
    categories: [
      { id: 'all', label: 'Tous les clichés' },
      { id: 'histoire', label: 'Notre Histoire' },
      { id: 'fiancailles', label: 'Fiançailles' },
      { id: 'lieu', label: 'Le Lieu' },
    ],
    items: [
      {
        id: '1',
        title: 'Notre histoire',
        category: 'histoire',
        imageUrl: '/photos/sir.jpeg',
        caption: 'Ajoutez ici la première photo dans public/photos/.',
      },
      {
        id: '2',
        title: 'Un moment précieux',
        category: 'histoire',
        imageUrl: '/photos/iletou.jpeg',
        caption: 'Ajoutez ici la deuxième photo dans public/photos/.',
      },
      {
        id: '3',
        title: 'Fiançailles',
        category: 'fiancailles',
        imageUrl: '/photos/tgt.jpeg',
        caption: 'Ajoutez ici une photo de vos fiançailles.',
      },
      {
        id: '4',
        title: 'À deux',
        category: 'histoire',
        imageUrl: '/photos/couple.jpeg',
        caption: 'Ajoutez ici une photo de votre choix.',
      },
      {
        id: '5',
        title: 'Souvenir',
        category: 'fiancailles',
        imageUrl: '/photos/rouge.jpeg',
        caption: 'Ajoutez ici une dernière photo souvenir.',
      },
    ] as GalleryItem[],
  },
  gifts: {
    title: 'Cadeaux & Cagnotte',
    description: 'Votre présence est de loin pour nous le plus beau des cadeaux. Toutefois, si vous souhaitez ajouter de la lumière à notre journée par un cadeau matériel, sentez-vous libre de le faire selon votre convenance. Si votre contribution est financière, vous pouvez participer à notre cagnotte par les différents moyens ci-dessous. Quel que soit le geste d’amour que vous aurez choisi de nous témoigner, il reste précieux à nos yeux.',
    transferDetails: [
      {
        provider: 'Mixx by Yas',
        label: 'Code de transfert mobile',
        value: '*145*1*1*montant*70880488*1ou2*code secret#',
        helpText: 'Remplacez « montant » et « code secret » par vos informations.',
      },
      {
        provider: 'Ecobank',
        label: 'N° de compte',
        value: '141793402001',
        helpText: 'Virement ou dépôt sur ce compte.',
      },
    ],
    onlineFundUrl: '',
    onlineFundLabel: 'Participer à la cagnotte en ligne',
  },
  rsvp: {
    eyebrow: 'Votre Réponse',
    title: 'Confirmer Votre Présence',
    subtitle: 'Merci de nous indiquer votre réponse avant le 5 Septembre 2026 afin de nous aider à tout orchestrer.',
    deadline: 'Réponse souhaitée avant le 5 Septembre 2026',
    fields: {
      lastName: 'Nom de famille',
      firstName: 'Prénom',
      email: 'Adresse E-mail',
      attending: 'Serez-vous parmi nous ?',
      yesOption: 'Oui, avec grand plaisir !',
      noOption: 'Non, c’est avec regret que je ne pourrai venir',
      guestCount: 'Nombre de personnes (vous inclus)',
      guestNames: 'Noms et prénoms des accompagnants',
      message: 'Un petit mot pour les mariés',
      submitBtn: 'Envoyer ma réponse',
      sendingBtn: 'Enregistrement en cours...',
    },
    successMessage: {
      title: 'Merci infiniment !',
      description: 'Votre réponse a bien été enregistrée. Nous avons tellement hâte de célébrer ce moment inoubliable avec vous !',
      modifyBtn: 'Modifier mes informations',
    },
  },
  footer: {
    thankYou: 'Merci du fond du cœur',
    quote: '« Aimer, ce n’est pas se regarder l’un l’autre, c’est regarder ensemble dans la même direction. »',
    author: 'Antoine de Saint-Exupéry',
    contactTitle: 'Une question ? Besoin d’aide ?',
    contactDetails: 'Écrivez-nous à iletouakpo@gmail.com ou contactez nos témoins.',
    copyright: '© 2026 Edwin & Julie — Avec tout notre amour',
  },
};
